### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by neocybereth**
changed betanet to mainnet

### CODE REVIEW

**Comment by stephenandrews** [comment]
Thanks

**Comment by neocybereth** [comment]
No worries. Let me know when it’s live so I can double-check to make sure all is good.

**Comment by stephenandrews** [comment]
Live now!

**Comment by neocybereth** [comment]
Alright, my browser must be serving up a cached page then because I’m seeing no changes. Is it working properly on your end?

**Comment by neocybereth** [comment]
There we go. I sent a new pull request with all the updated code and added a favicon.

**Pull request merged**
